In [1]:
!pip install datasets torch
!pip install accelerate -U
!pip install transformers -U

Requirement already satisfied: datasets in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (4.8.4)
Requirement already satisfied: torch in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (2.11.0)
Requirement already satisfied: filelock in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (from datasets) (3.25.2)
Requirement already satisfied: numpy>=1.17 in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (from datasets) (2.4.2)
Requirement already satisfied: pyarrow>=21.0.0 in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (from datasets) (23.0.1)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (from datasets) (0.4.1)
Requirement already satisfied: pandas in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (from datasets) (2.3.3)
Requirement already satisfied: requests>=2.32.2 in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (from datasets) (2.32.5)
Requirement already satisfied: httpx<1.0.0 in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (from datasets) (0.28.1)
Requirement already satisfied: tqdm>=4.66.3 in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (from datasets) (4.67.3)
Requirement already satisfied: xxhash in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (from datasets) (3.6.0)
Requirement already satisfied: multiprocess<0.70.20 in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (from datasets) (0.70.19)
Requirement already satisfied: fsspec<=2026.2.0,>=2023.1.0 in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (2026.2.0)
Requirement already satisfied: huggingface-hub<2.0,>=0.25.0 in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (from datasets) (1.8.0)
Requirement already satisfied: packaging in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (from datasets) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (from datasets) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (3.13.5)
Requirement already satisfied: anyio in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (from httpx<1.0.0->datasets) (4.13.0)
Requirement already satisfied: certifi in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (from httpx<1.0.0->datasets) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (from httpx<1.0.0->datasets) (1.0.9)
Requirement already satisfied: idna in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (from httpx<1.0.0->datasets) (3.11)
Requirement already satisfied: h11>=0.16 in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (from httpcore==1.*->httpx<1.0.0->datasets) (0.16.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (1.4.3)
Requirement already satisfied: typer in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (0.24.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (4.15.0)
Requirement already satisfied: setuptools<82 in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (from torch) (81.0.0)
Requirement already satisfied: sympy>=1.13.3 in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (from torch) (3.6.1)
Requirement already satisfied: jinja2 in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (from torch) (3.1.6)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.23.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (from requests>=2.32.2->datasets) (3.4.5)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (from requests>=2.32.2->datasets) (2.6.3)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (from jinja2->torch) (3.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (from pandas->datasets) (2026.1.post1)
Requirement already satisfied: tzdata>=2022.7 in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (from pandas->datasets) (2025.3)
Requirement already satisfied: six>=1.5 in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Requirement already satisfied: click>=8.2.1 in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (from typer->huggingface-hub<2.0,>=0.25.0->datasets) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (from typer->huggingface-hub<2.0,>=0.25.0->datasets) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (from typer->huggingface-hub<2.0,>=0.25.0->datasets) (14.3.3)
Requirement already satisfied: annotated-doc>=0.0.2 in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (from typer->huggingface-hub<2.0,>=0.25.0->datasets) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=0.25.0->datasets) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=0.25.0->datasets) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub<2.0,>=0.25.0->datasets) (0.1.2)

[notice] A new release of pip is available: 26.0 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
Requirement already satisfied: accelerate in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (1.13.0)
Requirement already satisfied: numpy>=1.17 in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (from accelerate) (2.4.2)
Requirement already satisfied: packaging>=20.0 in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (from accelerate) (26.0)
Requirement already satisfied: psutil in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (from accelerate) (7.2.2)
Requirement already satisfied: pyyaml in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (from accelerate) (6.0.3)
Requirement already satisfied: torch>=2.0.0 in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (from accelerate) (2.11.0)
Requirement already satisfied: huggingface_hub>=0.21.0 in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (from accelerate) (1.8.0)
Requirement already satisfied: safetensors>=0.4.3 in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (from accelerate) (0.7.0)
Requirement already satisfied: filelock>=3.10.0 in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (from huggingface_hub>=0.21.0->accelerate) (3.25.2)
Requirement already satisfied: fsspec>=2023.5.0 in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (from huggingface_hub>=0.21.0->accelerate) (2026.2.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (from huggingface_hub>=0.21.0->accelerate) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (from huggingface_hub>=0.21.0->accelerate) (0.28.1)
Requirement already satisfied: tqdm>=4.42.1 in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (from huggingface_hub>=0.21.0->accelerate) (4.67.3)
Requirement already satisfied: typer in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (from huggingface_hub>=0.21.0->accelerate) (0.24.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (from huggingface_hub>=0.21.0->accelerate) (4.15.0)
Requirement already satisfied: anyio in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (4.13.0)
Requirement already satisfied: certifi in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (1.0.9)
Requirement already satisfied: idna in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (3.11)
Requirement already satisfied: h11>=0.16 in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (0.16.0)
Requirement already satisfied: setuptools<82 in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (from torch>=2.0.0->accelerate) (81.0.0)
Requirement already satisfied: sympy>=1.13.3 in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (from torch>=2.0.0->accelerate) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (from torch>=2.0.0->accelerate) (3.6.1)
Requirement already satisfied: jinja2 in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (from torch>=2.0.0->accelerate) (3.1.6)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (from sympy>=1.13.3->torch>=2.0.0->accelerate) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (from jinja2->torch>=2.0.0->accelerate) (3.0.3)
Requirement already satisfied: click>=8.2.1 in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (from typer->huggingface_hub>=0.21.0->accelerate) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (from typer->huggingface_hub>=0.21.0->accelerate) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (from typer->huggingface_hub>=0.21.0->accelerate) (14.3.3)
Requirement already satisfied: annotated-doc>=0.0.2 in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (from typer->huggingface_hub>=0.21.0->accelerate) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (from rich>=12.3.0->typer->huggingface_hub>=0.21.0->accelerate) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (from rich>=12.3.0->typer->huggingface_hub>=0.21.0->accelerate) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface_hub>=0.21.0->accelerate) (0.1.2)

[notice] A new release of pip is available: 26.0 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
Requirement already satisfied: transformers in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (5.5.4)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (from transformers) (1.8.0)
Requirement already satisfied: numpy>=1.17 in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (from transformers) (2.4.2)
Requirement already satisfied: packaging>=20.0 in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (from transformers) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (from transformers) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (from transformers) (2026.3.32)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (from transformers) (0.22.2)
Requirement already satisfied: typer in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (from transformers) (0.24.1)
Requirement already satisfied: safetensors>=0.4.3 in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (from transformers) (4.67.3)
Requirement already satisfied: filelock>=3.10.0 in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (3.25.2)
Requirement already satisfied: fsspec>=2023.5.0 in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (2026.2.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (4.15.0)
Requirement already satisfied: anyio in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (4.13.0)
Requirement already satisfied: certifi in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.0.9)
Requirement already satisfied: idna in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (3.11)
Requirement already satisfied: h11>=0.16 in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.16.0)
Requirement already satisfied: click>=8.2.1 in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (from typer->transformers) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (from typer->transformers) (14.3.3)
Requirement already satisfied: annotated-doc>=0.0.2 in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (from typer->transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (from rich>=12.3.0->typer->transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (from rich>=12.3.0->typer->transformers) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /Users/alexanderflores/Desktop/agr/.venv/lib/python3.12/site-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->transformers) (0.1.2)

[notice] A new release of pip is available: 26.0 -> 26.0.1
[notice] To update, run: pip install --upgrade pip

In [2]:
'''
Examples of tokenization

Sometimes they do unsual things:

Ġ is a special character called the "zero-width non-joiner" represented as U+2581.
It is used in the tokenization process of GPT-2,
which utilize the byte pair encoding (BPE) method.

'''

from transformers import GPT2Tokenizer

tokenizer = GPT2Tokenizer.from_pretrained("gpt2")
text1 = "intensification"
tokens = tokenizer.tokenize(text1)

# return_tensors="pt": the tokenizer will output the sequence of tokens as a PyTorch tensor
input_ids = tokenizer.encode(text1, return_tensors="pt")

print("Text:", text1)
print("Tokens:", tokens)
print("Input IDs:", input_ids)

text2 = "how are you?"
tokens = tokenizer.tokenize(text2)
input_ids = tokenizer.encode(text2, return_tensors="pt")

print("Text:", text2)
print("Tokens:", tokens)
print("Input IDs:", input_ids)


# Note in the tokenization, there is no Ġ in front of "lock", because it is
# not a new word following the previous word.
text3 = "unlock the door"
tokens = tokenizer.tokenize(text3)
input_ids = tokenizer.encode(text3, return_tensors="pt")

print("Text:", text3)
print("Tokens:", tokens)
print("Input IDs:", input_ids)

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

Text: intensification
Tokens: ['int', 'ens', 'ification']
Input IDs: tensor([[ 600,  641, 2649]])
Text: how are you?
Tokens: ['how', 'Ġare', 'Ġyou', '?']
Input IDs: tensor([[4919,  389,  345,   30]])
Text: unlock the door
Tokens: ['un', 'lock', 'Ġthe', 'Ġdoor']
Input IDs: tensor([[ 403, 5354,  262, 3420]])

In [3]:
input_ids.shape

torch.Size([1, 4])

In [4]:
import torch


# Set device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
device

device(type='cpu')

In [5]:
# Decode text output

new_text = 'to be or not to be'

# 1. this is the same as tokenizer.tokenize(text2)
# 2. the to(device) at the end is very important -- otherwise this quantity exists on cpu
input_ids = tokenizer.encode(new_text, return_tensors="pt").to(device)

In [6]:
# define model

from transformers import GPT2LMHeadModel

model = GPT2LMHeadModel.from_pretrained("gpt2").to(device)

# Generate output
output = model.generate(input_ids, max_length=50)

print(output[0])

config.json:   0%|          | 0.00/665 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/548M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
The attention mask is not set and cannot be inferred from input because pad token is same as eos token. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.

tensor([1462,  307,  393,  407,  284,  307,   13,  198,  198,  464,  717, 1517,
         284,  466,  318,  284,  787, 1654,  326,  345,  389,  407, 1262,  262,
        2642, 3788,   13,  198,  198, 1532,  345,  389, 1262,  257, 1180, 3788,
          11,  345,  815,  307, 1498,  284,  779,  340, 1231,  597, 2761,   13,
         198,  198])

In [7]:
generated_text = tokenizer.decode(output[0], skip_special_tokens=True)
print(generated_text)

to be or not to be.

The first thing to do is to make sure that you are not using the wrong software.

If you are using a different software, you should be able to use it without any problems.

In [8]:
model.save_pretrained('./my_finetuned_gpt2')

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

In [9]:
# You can also save it to google drive -- see notebooks from before

## Pandas

In [10]:
import pandas as pd

# Creating a DataFrame
data = {
    'Name': ['Alice', 'Sanjay', 'Charlie', 'David', 'Maya'],
    'Age': [25, 30, 35, 40, 45],
    'City': ['New York', 'Seattle', 'Chicago', 'San Francisco', 'Phoenix']
}



df = pd.DataFrame(data)

# Extending with more entries
additional_data = {
    'Name': ['Ada', 'Grace', 'Helen', 'Ian', 'Julia', 'Ming', 'Linda', 'Mike', 'Nora', 'Oliver'],
    'Age': [50, 55, 60, 65, 70, 75, 80, 85, 90, 95],
    'City': ['San Francisco', 'Chicago', 'Seattle', 'Denver', 'Atlanta', 'Dallaa', 'Seattle', 'San Francisco', 'Dallas', 'Phoenix']
}

# Creating an extended DataFrame
extended_data = pd.DataFrame(additional_data)
long_df = pd.concat([df, extended_data], ignore_index=True)


long_df

       Name  Age           City
0     Alice   25       New York
1    Sanjay   30        Seattle
2   Charlie   35        Chicago
3     David   40  San Francisco
4      Maya   45        Phoenix
5       Ada   50  San Francisco
6     Grace   55        Chicago
7     Helen   60        Seattle
8       Ian   65         Denver
9     Julia   70        Atlanta
10     Ming   75         Dallaa
11    Linda   80        Seattle
12     Mike   85  San Francisco
13     Nora   90         Dallas
14   Oliver   95        Phoenix

In [11]:
# Saving the DataFrame to a CSV file
csv_path = 'friends.csv'
long_df.to_csv(csv_path, index=False)

csv_path

'friends.csv'

In [12]:
long_df

       Name  Age           City
0     Alice   25       New York
1    Sanjay   30        Seattle
2   Charlie   35        Chicago
3     David   40  San Francisco
4      Maya   45        Phoenix
5       Ada   50  San Francisco
6     Grace   55        Chicago
7     Helen   60        Seattle
8       Ian   65         Denver
9     Julia   70        Atlanta
10     Ming   75         Dallaa
11    Linda   80        Seattle
12     Mike   85  San Francisco
13     Nora   90         Dallas
14   Oliver   95        Phoenix

In [13]:
print(long_df)

       Name  Age           City
0     Alice   25       New York
1    Sanjay   30        Seattle
2   Charlie   35        Chicago
3     David   40  San Francisco
4      Maya   45        Phoenix
5       Ada   50  San Francisco
6     Grace   55        Chicago
7     Helen   60        Seattle
8       Ian   65         Denver
9     Julia   70        Atlanta
10     Ming   75         Dallaa
11    Linda   80        Seattle
12     Mike   85  San Francisco
13     Nora   90         Dallas
14   Oliver   95        Phoenix

In [14]:
import pandas as pd

# Load data from a CSV file
df = pd.read_csv('friends.csv')

# Display the first few rows of the dataframe
print(df.head())

      Name  Age           City
0    Alice   25       New York
1   Sanjay   30        Seattle
2  Charlie   35        Chicago
3    David   40  San Francisco
4     Maya   45        Phoenix

In [15]:
df.tail()

      Name  Age           City
10    Ming   75         Dallaa
11   Linda   80        Seattle
12    Mike   85  San Francisco
13    Nora   90         Dallas
14  Oliver   95        Phoenix

In [16]:
df

       Name  Age           City
0     Alice   25       New York
1    Sanjay   30        Seattle
2   Charlie   35        Chicago
3     David   40  San Francisco
4      Maya   45        Phoenix
5       Ada   50  San Francisco
6     Grace   55        Chicago
7     Helen   60        Seattle
8       Ian   65         Denver
9     Julia   70        Atlanta
10     Ming   75         Dallaa
11    Linda   80        Seattle
12     Mike   85  San Francisco
13     Nora   90         Dallas
14   Oliver   95        Phoenix

In [17]:
df['Age'] >= 65

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8      True
9      True
10     True
11     True
12     True
13     True
14     True
Name: Age, dtype: bool

In [18]:
# Assume 'df' is a DataFrame containing employee data
older_friends = df[df['Age'] >= 65]

# Display the result
print(older_friends)

      Name  Age           City
8      Ian   65         Denver
9    Julia   70        Atlanta
10    Ming   75         Dallaa
11   Linda   80        Seattle
12    Mike   85  San Francisco
13    Nora   90         Dallas
14  Oliver   95        Phoenix

In [19]:
sf_age = df[df['City'] == 'San Francisco']['Age'].mean()

# Display the result
print(sf_age)

58.333333333333336

In [20]:
# Adding a new column
df['Age_in_2020'] = df['Age'] - 4

# Removing a column
df.drop('Age', axis=1, inplace=True)

In [21]:
df

       Name           City  Age_in_2020
0     Alice       New York           21
1    Sanjay        Seattle           26
2   Charlie        Chicago           31
3     David  San Francisco           36
4      Maya        Phoenix           41
5       Ada  San Francisco           46
6     Grace        Chicago           51
7     Helen        Seattle           56
8       Ian         Denver           61
9     Julia        Atlanta           66
10     Ming         Dallaa           71
11    Linda        Seattle           76
12     Mike  San Francisco           81
13     Nora         Dallas           86
14   Oliver        Phoenix           91

## Breakout Exercise 1: Load and Inspect Data
Load the Iris dataset from a provided CSV file and display the first and last 5 rows of the dataset. Additionally, print the summary statistics of the dataset.

## Breakout Exercise 2: Data Filtering

From the loaded Iris dataset, extract rows where the petal length is greater than 1.5 and petal width is less than 0.5.

## Break Exercise 3: Column Operations

Add a new column to the Iris dataset called 'sepal_area' calculated as the product of sepal length and sepal width.

## Breakout Exercise 4: Data Grouping and Visualization

Group the Iris dataset by species, compute the average of all numeric columns for each species, and create a bar chart visualizing

- the average sepal length and petal length for each species.
- the average sepal width and petal width for each species.
- the average sepal length and sepal width for each species.
- the average petal length and petal width for each species.

## Breakout Exercise 5:

- Use two of the four measurements (petal length and width, septal length and width) to building a MLP classifier for the iris varieities

        (Later, you can also consider to show the boundaries on this 2D space)
        
- Use all four features to classify