In [2]:
import pandas as pd
import numpy as np
import statsmodels.formula.api
import seaborn as sns 
import matplotlib.pyplot as plt

In [5]:
df = pd.read_csv("/Users/jjburrell/Downloads/school_data.csv")

In [6]:
df.describe().T
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 467 entries, 0 to 466
Data columns (total 31 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   v1                    467 non-null    int64
 1   schoolid              467 non-null    int64
 2   schoolname            467 non-null    object
 3   submissiondate        467 non-null    object
 4   district              467 non-null    object
 5   householdincome2005   467 non-null    float64
 6   householdincome2015   467 non-null    float64
 7   curriculumchange1     467 non-null    object
 8   curriculumchange2     174 non-null    object
 9   curriculumchange3     63 non-null     object
 10  mathematicsscore2000  467 non-null    int64
 11  mathematicsscore2001  467 non-null    int64
 12  mathematicsscore2002  467 non-null    int64
 13  mathematicsscore2003  467 non-null    int64
 14  mathematicsscore2004  467 non-null    int64
 15  mathematicsscore2005  467 non-null    int64
 16  mathematicsscore2006  467 non-null    int64
 17  mathematicsscore2007  467 non-null    int64
 18  mathematicsscore2008  467 non-null    int64
 19  mathematicsscore2009  467 non-null    int64
 20  mathematicsscore2010  467 non-null    int64
 21  mathematicsscore2011  467 non-null    float64
 22  mathematicsscore2012  467 non-null    float64
 23  mathematicsscore2013  467 non-null    float64
 24  mathematicsscore2014  467 non-null    float64
 25  mathematicsscore2015  467 non-null    float64
 26  mathematicsscore2016  467 non-null    float64
 27  mathematicsscore2017  467 non-null    float64
 28  mathematicsscore2018  467 non-null    float64
 29  mathematicsscore2019  467 non-null    float64
 30  districtcode          467 non-null    int64
dtypes: float64(11), int64(14), object(6)
memory usage: 113.2+ KB

    v1  schoolid  ... mathematicsscore2019 districtcode
0  337   2818384  ...                894.0            1
1   70   4347604  ...                496.0            8
2   17   3995316  ...                815.0            6
3   57   1087900  ...                420.0            1
4  213   4554916  ...                896.0            7

[5 rows x 31 columns]

In [8]:
df.isna()

        v1  schoolid  ...  mathematicsscore2019  districtcode
0    False     False  ...                 False         False
1    False     False  ...                 False         False
2    False     False  ...                 False         False
3    False     False  ...                 False         False
4    False     False  ...                 False         False
..     ...       ...  ...                   ...           ...
462  False     False  ...                 False         False
463  False     False  ...                 False         False
464  False     False  ...                 False         False
465  False     False  ...                 False         False
466  False     False  ...                 False         False

[467 rows x 31 columns]

In [ ]:
df = df.drop(index=('householdincome2005', ))

KeyError: '[False] not found in axis'

In [14]:
df['district']

0            Cross Roads Independent School District
1                Wheeler Independent School District
2                   Terlingua Common School District
3            Cross Roads Independent School District
4      Round Top-Carmine Independent School District
                           ...
462    Round Top-Carmine Independent School District
463                 Hart Independent School District
464               Gruver Independent School District
465              Wheeler Independent School District
466              Wheeler Independent School District
Name: district, Length: 467, dtype: object

In [ ]:
inddist = []
df = df[['district', 'householdincome2005']].mean()

TypeError: Could not convert ['Cross Roads Independent School DistrictWheeler Independent School DistrictTerlingua Common School DistrictCross Roads Independent School DistrictRound Top-Carmine Independent School DistrictHart Independent School DistrictFort Hancock Independent School DistrictWheeler Independent School DistrictHart Independent School DistrictTerlingua Common School DistrictRound Top-Carmine Independent School DistrictGruver Independent School DistrictCross Roads Independent School DistrictHart Independent School DistrictGruver Independent School DistrictFort Hancock Independent School DistrictHart Independent School DistrictFort Hancock Independent School DistrictWheeler Independent School DistrictWheeler Independent School DistrictWheeler Independent School DistrictTerlingua Common School DistrictHart Independent School DistrictTerlingua Common School DistrictGruver Independent School DistrictHart Independent School DistrictTerlingua Common School DistrictFort Hancock Independent School DistrictFort Hancock Independent School DistrictHart Independent School DistrictWheeler Independent School DistrictWheeler Independent School DistrictGruver Independent School DistrictDe Kalb Independent School DistrictFort Hancock Independent School DistrictWheeler Independent School DistrictOrangefield Independent School DistrictHart Independent School DistrictGruver Independent School DistrictWheeler Independent School DistrictGruver Independent School DistrictTerlingua Common School DistrictWheeler Independent School DistrictOrangefield Independent School DistrictHart Independent School DistrictFort Hancock Independent School DistrictWheeler Independent School DistrictOrangefield Independent School DistrictHart Independent School DistrictHart Independent School DistrictRound Top-Carmine Independent School DistrictHart Independent School DistrictWheeler Independent School DistrictTerlingua Common School DistrictFort Hancock Independent School DistrictHart Independent School DistrictHart Independent School DistrictWheeler Independent School DistrictWheeler Independent School DistrictFort Hancock Independent School DistrictTerlingua Common School DistrictRound Top-Carmine Independent School DistrictWheeler Independent School DistrictFort Hancock Independent School DistrictDe Kalb Independent School DistrictDe Kalb Independent School DistrictHart Independent School DistrictGruver Independent School DistrictOrangefield Independent School DistrictRound Top-Carmine Independent School DistrictGruver Independent School DistrictHart Independent School DistrictTerlingua Common School DistrictCross Roads Independent School DistrictHart Independent School DistrictOrangefield Independent School DistrictRound Top-Carmine Independent School DistrictHart Independent School DistrictRound Top-Carmine Independent School DistrictGruver Independent School DistrictTerlingua Common School DistrictHart Independent School DistrictTerlingua Common School DistrictWheeler Independent School DistrictWheeler Independent School DistrictGruver Independent School DistrictOrangefield Independent School DistrictWheeler Independent School DistrictWheeler Independent School DistrictWheeler Independent School DistrictTerlingua Common School DistrictWheeler Independent School DistrictTerlingua Common School DistrictGruver Independent School DistrictOrangefield Independent School DistrictHart Independent School DistrictRound Top-Carmine Independent School DistrictHart Independent School DistrictHart Independent School DistrictGruver Independent School DistrictHart Independent School DistrictGruver Independent School DistrictRound Top-Carmine Independent School DistrictGruver Independent School DistrictDe Kalb Independent School DistrictFort Hancock Independent School DistrictFort Hancock Independent School DistrictGruver Independent School DistrictWheeler Independent School DistrictFort Hancock Independent School DistrictHart Independent School DistrictHart Independent School DistrictHart Independent School DistrictDe Kalb Independent School DistrictDe Kalb Independent School DistrictCross Roads Independent School DistrictCross Roads Independent School DistrictGruver Independent School DistrictTerlingua Common School DistrictWheeler Independent School DistrictHart Independent School DistrictFort Hancock Independent School DistrictCross Roads Independent School DistrictHart Independent School DistrictGruver Independent School DistrictFort Hancock Independent School DistrictTerlingua Common School DistrictHart Independent School DistrictWheeler Independent School DistrictDe Kalb Independent School DistrictHart Independent School DistrictWheeler Independent School DistrictOrangefield Independent School DistrictWheeler Independent School DistrictHart Independent School DistrictFort Hancock Independent School DistrictWheeler Independent School DistrictDe Kalb Independent School DistrictRound Top-Carmine Independent School DistrictRound Top-Carmine Independent School DistrictFort Hancock Independent School DistrictDe Kalb Independent School DistrictWheeler Independent School DistrictWheeler Independent School DistrictHart Independent School DistrictFort Hancock Independent School DistrictGruver Independent School DistrictDe Kalb Independent School DistrictHart Independent School DistrictFort Hancock Independent School DistrictWheeler Independent School DistrictTerlingua Common School DistrictHart Independent School DistrictGruver Independent School DistrictHart Independent School DistrictGruver Independent School DistrictGruver Independent School DistrictDe Kalb Independent School DistrictFort Hancock Independent School DistrictTerlingua Common School DistrictHart Independent School DistrictHart Independent School DistrictOrangefield Independent School DistrictDe Kalb Independent School DistrictRound Top-Carmine Independent School DistrictTerlingua Common School DistrictTerlingua Common School DistrictRound Top-Carmine Independent School DistrictGruver Independent School DistrictHart Independent School DistrictRound Top-Carmine Independent School DistrictFort Hancock Independent School DistrictWheeler Independent School DistrictHart Independent School DistrictHart Independent School DistrictHart Independent School DistrictHart Independent School DistrictCross Roads Independent School DistrictDe Kalb Independent School DistrictHart Independent School DistrictHart Independent School DistrictHart Independent School DistrictGruver Independent School DistrictRound Top-Carmine Independent School DistrictHart Independent School DistrictHart Independent School DistrictWheeler Independent School DistrictDe Kalb Independent School DistrictDe Kalb Independent School DistrictGruver Independent School DistrictRound Top-Carmine Independent School DistrictGruver Independent School DistrictHart Independent School DistrictWheeler Independent School DistrictDe Kalb Independent School DistrictHart Independent School DistrictWheeler Independent School DistrictDe Kalb Independent School DistrictDe Kalb Independent School DistrictCross Roads Independent School DistrictGruver Independent School DistrictDe Kalb Independent School DistrictHart Independent School DistrictFort Hancock Independent School DistrictRound Top-Carmine Independent School DistrictRound Top-Carmine Independent School DistrictWheeler Independent School DistrictFort Hancock Independent School DistrictHart Independent School DistrictDe Kalb Independent School DistrictHart Independent School DistrictHart Independent School DistrictGruver Independent School DistrictFort Hancock Independent School DistrictHart Independent School DistrictFort Hancock Independent School DistrictFort Hancock Independent School DistrictHart Independent School DistrictHart Independent School DistrictHart Independent School DistrictHart Independent School DistrictWheeler Independent School DistrictDe Kalb Independent School DistrictGruver Independent School DistrictHart Independent School DistrictRound Top-Carmine Independent School DistrictTerlingua Common School DistrictHart Independent School DistrictFort Hancock Independent School DistrictWheeler Independent School DistrictRound Top-Carmine Independent School DistrictGruver Independent School DistrictHart Independent School DistrictHart Independent School DistrictGruver Independent School DistrictWheeler Independent School DistrictHart Independent School DistrictOrangefield Independent School DistrictRound Top-Carmine Independent School DistrictWheeler Independent School DistrictHart Independent School DistrictRound Top-Carmine Independent School DistrictRound Top-Carmine Independent School DistrictWheeler Independent School DistrictRound Top-Carmine Independent School DistrictOrangefield Independent School DistrictOrangefield Independent School DistrictDe Kalb Independent School DistrictWheeler Independent School DistrictDe Kalb Independent School DistrictFort Hancock Independent School DistrictWheeler Independent School DistrictWheeler Independent School DistrictRound Top-Carmine Independent School DistrictHart Independent School DistrictRound Top-Carmine Independent School DistrictCross Roads Independent School DistrictWheeler Independent School DistrictGruver Independent School DistrictDe Kalb Independent School DistrictWheeler Independent School DistrictRound Top-Carmine Independent School DistrictWheeler Independent School DistrictTerlingua Common School DistrictTerlingua Common School DistrictTerlingua Common School DistrictGruver Independent School DistrictWheeler Independent School DistrictHart Independent School DistrictWheeler Independent School DistrictRound Top-Carmine Independent School DistrictHart Independent School DistrictRound Top-Carmine Independent School DistrictHart Independent School DistrictDe Kalb Independent School DistrictHart Independent School DistrictRound Top-Carmine Independent School DistrictOrangefield Independent School DistrictTerlingua Common School DistrictTerlingua Common School DistrictGruver Independent School DistrictRound Top-Carmine Independent School DistrictCross Roads Independent School DistrictHart Independent School DistrictDe Kalb Independent School DistrictDe Kalb Independent School DistrictHart Independent School DistrictRound Top-Carmine Independent School DistrictOrangefield Independent School DistrictDe Kalb Independent School DistrictGruver Independent School DistrictHart Independent School DistrictHart Independent School DistrictFort Hancock Independent School DistrictHart Independent School DistrictFort Hancock Independent School DistrictHart Independent School DistrictFort Hancock Independent School DistrictGruver Independent School DistrictHart Independent School DistrictGruver Independent School DistrictCross Roads Independent School DistrictRound Top-Carmine Independent School DistrictHart Independent School DistrictHart Independent School DistrictWheeler Independent School DistrictGruver Independent School DistrictGruver Independent School DistrictGruver Independent School DistrictHart Independent School DistrictTerlingua Common School DistrictFort Hancock Independent School DistrictDe Kalb Independent School DistrictFort Hancock Independent School DistrictWheeler Independent School DistrictGruver Independent School DistrictOrangefield Independent School DistrictOrangefield Independent School DistrictDe Kalb Independent School DistrictOrangefield Independent School DistrictCross Roads Independent School DistrictWheeler Independent School DistrictCross Roads Independent School DistrictGruver Independent School DistrictHart Independent School DistrictGruver Independent School DistrictHart Independent School DistrictDe Kalb Independent School DistrictDe Kalb Independent School DistrictHart Independent School DistrictTerlingua Common School DistrictHart Independent School DistrictRound Top-Carmine Independent School DistrictWheeler Independent School DistrictFort Hancock Independent School DistrictWheeler Independent School DistrictRound Top-Carmine Independent School DistrictHart Independent School DistrictWheeler Independent School DistrictHart Independent School DistrictCross Roads Independent School DistrictWheeler Independent School DistrictDe Kalb Independent School DistrictGruver Independent School DistrictOrangefield Independent School DistrictOrangefield Independent School DistrictHart Independent School DistrictDe Kalb Independent School DistrictOrangefield Independent School DistrictGruver Independent School DistrictCross Roads Independent School DistrictDe Kalb Independent School DistrictOrangefield Independent School DistrictFort Hancock Independent School DistrictWheeler Independent School DistrictTerlingua Common School DistrictOrangefield Independent School DistrictTerlingua Common School DistrictRound Top-Carmine Independent School DistrictTerlingua Common School DistrictWheeler Independent School DistrictHart Independent School DistrictDe Kalb Independent School DistrictHart Independent School DistrictWheeler Independent School DistrictHart Independent School DistrictRound Top-Carmine Independent School DistrictCross Roads Independent School DistrictHart Independent School DistrictWheeler Independent School DistrictHart Independent School DistrictHart Independent School DistrictCross Roads Independent School DistrictCross Roads Independent School DistrictWheeler Independent School DistrictHart Independent School DistrictRound Top-Carmine Independent School DistrictHart Independent School DistrictWheeler Independent School DistrictFort Hancock Independent School DistrictOrangefield Independent School DistrictGruver Independent School DistrictWheeler Independent School DistrictHart Independent School DistrictRound Top-Carmine Independent School DistrictHart Independent School DistrictWheeler Independent School DistrictHart Independent School DistrictWheeler Independent School DistrictOrangefield Independent School DistrictHart Independent School DistrictHart Independent School DistrictDe Kalb Independent School DistrictWheeler Independent School DistrictGruver Independent School DistrictHart Independent School DistrictGruver Independent School DistrictHart Independent School DistrictGruver Independent School DistrictWheeler Independent School DistrictWheeler Independent School DistrictOrangefield Independent School DistrictOrangefield Independent School DistrictWheeler Independent School DistrictWheeler Independent School DistrictWheeler Independent School DistrictFort Hancock Independent School DistrictDe Kalb Independent School DistrictFort Hancock Independent School DistrictGruver Independent School DistrictFort Hancock Independent School DistrictDe Kalb Independent School DistrictWheeler Independent School DistrictFort Hancock Independent School DistrictGruver Independent School DistrictFort Hancock Independent School DistrictRound Top-Carmine Independent School DistrictWheeler Independent School DistrictGruver Independent School DistrictGruver Independent School DistrictHart Independent School DistrictDe Kalb Independent School DistrictWheeler Independent School DistrictWheeler Independent School DistrictDe Kalb Independent School DistrictDe Kalb Independent School DistrictTerlingua Common School DistrictHart Independent School DistrictHart Independent School DistrictGruver Independent School DistrictHart Independent School DistrictRound Top-Carmine Independent School DistrictWheeler Independent School DistrictWheeler Independent School DistrictOrangefield Independent School DistrictHart Independent School DistrictWheeler Independent School DistrictHart Independent School DistrictTerlingua Common School DistrictHart Independent School DistrictHart Independent School DistrictGruver Independent School DistrictRound Top-Carmine Independent School DistrictHart Independent School DistrictTerlingua Common School DistrictTerlingua Common School DistrictHart Independent School DistrictWheeler Independent School DistrictGruver Independent School DistrictHart Independent School DistrictWheeler Independent School DistrictHart Independent School DistrictDe Kalb Independent School DistrictGruver Independent School DistrictOrangefield Independent School DistrictOrangefield Independent School DistrictCross Roads Independent School DistrictWheeler Independent School DistrictHart Independent School DistrictFort Hancock Independent School DistrictRound Top-Carmine Independent School DistrictWheeler Independent School DistrictRound Top-Carmine Independent School DistrictHart Independent School DistrictGruver Independent School DistrictWheeler Independent School DistrictWheeler Independent School District'] to numeric

In [ ]:
df[df['district'] == 'Hart Independent School District'].describe()

#df[['Hart Independent School District']].describe()
#df[['district', 'districtcode']].value_counts

              v1      schoolid  ...  mathematicsscore2019  districtcode
count  115.00000  1.150000e+02  ...            115.000000    115.000000
mean   215.00000  3.943827e+06  ...            586.156522      2.947826
std    128.07317  1.261382e+06  ...            179.445764      0.223351
min      8.00000  2.474000e+04  ...            156.000000      2.000000
25%    107.50000  3.419354e+06  ...            474.500000      3.000000
50%    211.00000  4.149968e+06  ...            604.000000      3.000000
75%    312.50000  4.626218e+06  ...            699.000000      3.000000
max    463.00000  5.791580e+06  ...            999.000000      3.000000

[8 rows x 25 columns]

In [ ]:
import model.ols 
    math